name: release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore: release')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm ci
          git config --unset core.hooksPath

      - name: Build
        run: npm run compile

      - name: Bump versions
        run: npx lerna version --yes --no-private
        # run: npx lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Reconfigure registry URL
        uses: actions/setup-node@v3.3.0
        with:
          registry-url: 'https://npm.pkg.github.com/'

      - name: Configure NPM
        run: |
          echo "@appfolio:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> .npmrc

      - name: Publish to GitHub Packages
        run: npx lerna publish from-git --yes
        # run: npx lerna publish from-git --yes --include-private "*"

      - name: Reconfigure registry URL
        uses: actions/setup-node@v3.3.0
        with:
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure NPM
        run: |
          echo "registry=https://registry.npmjs.org" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Publish to NPM
        run: npx lerna publish from-git --yes
